Repository elastic/elastic-agent-inputs, pull requests merged in 2022-09, with the labels that each got.

#44 jjbb: use fleet-ci
  .ci/jobs/defaults.yml
  .ci/jobs/elastic-agent-inputs-mbp.yml
Labels: Team:Automation, automation

#45 [automation] Update go release version 1.18.6
  .go-version
  .golangci.yml
Labels: automation, dependency

#43 Add V2 client to the load generator
  NOTICE.txt
  go.mod
  go.sum
  inputs/loadgenerator/config.go
  inputs/loadgenerator/core.go
  inputs/loadgenerator/core_test.go
  inputs/loadgenerator/loadgenerator.go
Labels: Team:Elastic-Agent-Data-Plane
